MyApp\BackofficeBundle\Entity\Category:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        position:
            type: integer
    lifecycleCallbacks: {  }
