MyApp\BackofficeBundle\Entity\Departement:
    type: entity
    table: null
    repositoryClass: MyApp\BackofficeBundle\Entity\DepartementRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        position:
            type: string
            length: 255
    lifecycleCallbacks: {  }
