
my_app_frontoffice_user_add:
    pattern:  /add
    defaults: { _controller: MyAppFrontofficeBundle:user:add }
    
my_app_frontoffice_user_show:
    pattern:  /show
    defaults: { _controller: MyAppFrontofficeBundle:user:show }
    
my_app_frontoffice_user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: MyAppFrontofficeBundle:user:delete }  
       
my_app_frontoffice_user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: MyAppFrontofficeBundle:user:edit }  
    
my_app_frontoffice_user_voir:
    pattern:  /{id}/voir
    defaults: { _controller: MyAppFrontofficeBundle:user:voir }    
    
    
    
my_app_frontoffice_user_manage:
    pattern:  /manage
    defaults: { _controller: MyAppFrontofficeBundle:user:manage}
    
 