my_app_utilisateur:
    resource: "@MyAppUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

#my_app_user:
#    resource: "@MyAppUserBundle/Resources/config/routing.yml"
#    prefix:   /

my_app_frontoffice:
    resource: "@MyAppFrontofficeBundle/Resources/config/routing.yml"
    prefix:   /

my_app_backoffice:
    resource: "@MyAppBackofficeBundle/Resources/config/routing.yml"
    prefix:   /admin

activerCompte:
    path:     /account/activate/{idtoken}
    defaults: { _controller: MyAppBackofficeBundle:admin:activerCompteAdmin }

# app/config/routing.yml

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

 