

my_app_frontoffice_homepage:
    path:     /index.php
    defaults: { _controller: MyAppFrontofficeBundle:Default:index }
    
    
my_app_frontoffice_authentification_inscription:
    path:     /authentification
    defaults: { _controller: MyAppFrontofficeBundle:Default:authentification }
 
 
my_app_frontoffice_about:
    path:     /about
    defaults: { _controller: MyAppFrontofficeBundle:Default:about }
    
    
my_app_frontoffice_contact:
    path:     /contact
    defaults: { _controller: MyAppFrontofficeBundle:Default:contact }   
    
    
    
my_app_frontoffice_blog:
    path:     /blog
    defaults: { _controller: MyAppFrontofficeBundle:Default:blog }   
    
    
    
my_app_frontoffice_faq:
    path:     /faq
    defaults: { _controller: MyAppFrontofficeBundle:Default:faq }  
    
    
    
my_app_frontoffice_terms:
    path:     /terms
    defaults: { _controller: MyAppFrontofficeBundle:Default:terms }    
    
my_app_frontoffice_checkout:
    path:     /checkout
    defaults: { _controller: MyAppFrontofficeBundle:Default:checkout }     
    
my_app_frontoffice_cart:
    path:     /cart
    defaults: { _controller: MyAppFrontofficeBundle:Default:cart }    
 
#    
#fos_user_registration_register_client:
#    path:     /register
#    defaults: { _controller: FOSUserBundle:Registration:register }
#    
#fos_user_security_login_client:
#    path:     /login
#    defaults: { _controller: FOSUserBundle:Security:login }
#    
#fos_user_security_logout_client:
#    path:     /logout
#    defaults: { _controller: FOSUserBundle:Security:logout }
    