
my_app_frontoffice_homepage:
    path:     /index.php
    defaults: { _controller: MyAppFrontofficeBundle:client:index }

my_app_frontoffice_authentification_inscription:
    path:     /authentification
    defaults: { _controller: MyAppFrontofficeBundle:client:authentification }

    
my_app_frontoffice_contact:
    path:     /contact
    defaults: { _controller: MyAppFrontofficeBundle:message:add }
 #   defaults: { _controller: MyAppFrontofficeBundle:Default:contact }
    
my_app_frontoffice_about:
    path:     /about
    defaults: { _controller: MyAppFrontofficeBundle:client:about }

my_app_frontoffice_blog:
    path:     /blog
    defaults: { _controller: MyAppFrontofficeBundle:client:blog }

    
my_app_frontoffice_faq:
    path:     /faq
    defaults: { _controller: MyAppFrontofficeBundle:client:faq }
    
my_app_frontoffice_terms:
    path:     /terms
    defaults: { _controller: MyAppFrontofficeBundle:client:terms }
    
my_app_frontoffice_checkout:
    path:     /checkout
    defaults: { _controller: MyAppFrontofficeBundle:client:checkout }
    
my_app_frontoffice_cart:
    path:     /cart/{id}
    defaults: { _controller: MyAppFrontofficeBundle:client:cart }

my_app_frontoffice_singleproductsidebar:
    path:     /singleproductsidebar
    defaults: { _controller: MyAppFrontofficeBundle:client:singleproductsidebar }
    
my_app_frontoffice_singleproduct:
    path:     /singleproduct/{id}
    defaults: { _controller: MyAppFrontofficeBundle:client:singleproduct }

utilisateur:
    resource: "@MyAppBackofficeBundle/Resources/config/routing/utilisateur.yml"
    prefix: /utilisateur 
message:
    resource: "@MyAppFrontofficeBundle/Resources/config/routing/message.yml"
    prefix: /message
#    
#fos_user_registration_register_client:
#    path:     /register
#    defaults: { _controller: FOSUserBundle:Registration:register }
#    
#fos_user_security_login_client:
#    path:     /login
#    defaults: { _controller: FOSUserBundle:Security:login }
#    
#fos_user_security_logout_client:
#    path:     /logout
#    defaults: { _controller: FOSUserBundle:Security:logout }


my_app_frontoffice_supprimerdepanier:
    path:     /supprimerdepanier/{id}
    defaults: { _controller: MyAppFrontofficeBundle:client:supprimerdepanier }
    
my_app_frontoffice_supprimerdeshoppingcart:
    path:     /supprimerdeshoppingcart/{id}
    defaults: { _controller: MyAppFrontofficeBundle:client:supprimerdeshoppingcart }




#my_app_frontoffice_addquantity:
#    path:     /addquantity
#    defaults: { _controller: MyAppFrontofficeBundle:client:addquantity }
#
#
#    
#my_app_frontoffice_reducequantity:
#    path:     /reducequantity
#    defaults: { _controller: MyAppFrontofficeBundle:client:reducequantity }