services:
#    my_app_frontoffice.example:
#        class: MyApp\FrontofficeBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

services:  
    panier:
        class: %panier.manager.class%
        arguments: [@doctrine.orm.entity_manager,@service_container, @router ]

parameters:
    panier.manager.class: MyApp\FrontofficeBundle\Services\Panier

