services:
#    my_app_backoffice.example:
#        class: MyApp\BackofficeBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]



services:
    collectify_security_manager:
        class: %collectify.security.manager.class%
        arguments: [@doctrine.orm.entity_manager]


parameters:
    collectify.security.manager.class: MyApp\BackofficeBundle\Services\Security
    
    
    
