services:
#    my_app_backoffice.example:
#        class: MyApp\BackofficeBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]



services:
    collectify_security_manager:
        class: %collectify.security.manager.class%
        arguments: [@doctrine.orm.entity_manager,@service_container, @router ]
        
    collectify_mail_manager:
        class: %collectify.mail.manager.class%
        arguments: [@service_container]
    Valid:
        class: %collectify.Valid.manager.class%
        arguments: [@service_container]

parameters:
    collectify.security.manager.class: MyApp\BackofficeBundle\Services\Security
    collectify.mail.manager.class: MyApp\BackofficeBundle\Services\Mail
    collectify.Valid.manager.class: MyApp\BackofficeBundle\Services\Valid
    
    
