
my_app_backoffice_manage_message:
    pattern:  /message
    defaults: { _controller: MyAppBackofficeBundle:manage:message }
    
    
my_app_backoffice_manage_produit:
    pattern:  /produit
    defaults: { _controller: MyAppBackofficeBundle:manage:produit }
    
    
    
my_app_backoffice_manage_category_add:
    pattern:  /category
    defaults: { _controller: MyAppBackofficeBundle:manage:categoryadd }
    requirements:
        _method:  POST|GET
    options:
        expose: true   
        
my_app_backoffice_manage_category_delete:
    pattern:  /{id}/category
    defaults: { _controller: MyAppBackofficeBundle:manage:categorydelete }
    requirements:
        _method:  POST|GET
    options:
        expose: true    
        
my_app_backoffice_manage_category_edit:
    pattern:  /{id}/category
    defaults: { _controller: MyAppBackofficeBundle:manage:categoryedit }
    requirements:
        _method:  POST|GET
    options:
        expose: true     
    
    
    
    
    
    
    
    
my_app_backoffice_manage_state:
    pattern:  /state
    defaults: { _controller: MyAppBackofficeBundle:manage:state }
    
my_app_backoffice_manage_departement:
    pattern:  /departement
    defaults: { _controller: MyAppBackofficeBundle:manage:departement }